// automatically generated by the FlatBuffers compiler, do not modify

package protocol;

@SuppressWarnings("unused")
public final class InLogin extends Table {
    public static InLogin getRootAsInLogin(ByteBuffer _bb) {
        return getRootAsInLogin(_bb, new InLogin());
    }

    public static InLogin getRootAsInLogin(ByteBuffer _bb, InLogin obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createInLogin(FlatBufferBuilder builder,
                                    int account) throws Exception {
        builder.startObject(1);
        InLogin.addAccount(builder, account);
        return InLogin.endInLogin(builder);
    }

    public static void startInLogin(FlatBufferBuilder builder) throws Exception {
        builder.startObject(1);
    }

    public static void addAccount(FlatBufferBuilder builder, int account) throws Exception {
        builder.addInt(0, account, 0);
    }

    public static int endInLogin(FlatBufferBuilder builder) throws Exception {
        int o = builder.endObject();
        return o;
    }

    public static void finishInLoginBuffer(FlatBufferBuilder builder, int offset) throws Exception {
        builder.finish(offset);
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public InLogin __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public int account() {
        int o = __offset(4);
        return o != 0 ? bb.getInt(o + bb_pos) : 0;
    }
}

