// automatically generated by the FlatBuffers compiler, do not modify

package protocol;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class OutLogin extends Table {
    public static OutLogin getRootAsOutLogin(ByteBuffer _bb) {
        return getRootAsOutLogin(_bb, new OutLogin());
    }

    public static OutLogin getRootAsOutLogin(ByteBuffer _bb, OutLogin obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createOutLogin(FlatBufferBuilder builder,
                                     boolean hasRole) throws Exception {
        builder.startObject(1);
        OutLogin.addHasRole(builder, hasRole);
        return OutLogin.endOutLogin(builder);
    }

    public static void startOutLogin(FlatBufferBuilder builder) throws Exception {
        builder.startObject(1);
    }

    public static void addHasRole(FlatBufferBuilder builder, boolean hasRole) throws Exception {
        builder.addBoolean(0, hasRole, false);
    }

    public static int endOutLogin(FlatBufferBuilder builder) throws Exception {
        int o = builder.endObject();
        return o;
    }

    public static void finishOutLoginBuffer(FlatBufferBuilder builder, int offset) throws Exception {
        builder.finish(offset);
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public OutLogin __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public boolean hasRole() {
        int o = __offset(4);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }
}

